---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: practicacd
  labels:
    app: practicacd  
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: practicacd
  template:
    metadata:
      labels:
        app: practicacd
    spec:
      containers:
      - name: practicacd
        image: mastercloudapps/practicacd:1.0
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: practicacd
  labels:
    app: practicacd
spec:
  ports:
    - port: 80
  selector:
    app: practicacd
  type: LoadBalancer