---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: practicacd
  labels:
    app: practicacd  
spec:
  replicas: 3
  revisionHistoryLimit: 2
  strategy:
    canary:
      analysis:
        templates:
        - templateName: webcheck
      steps:
      - setWeight: 20
      - pause:
          duration: "30s"
      - setWeight: 50
      - pause:
          duration: "30s"
      - setWeight: 100      
  selector:
    matchLabels:
      app: practicacd
  template:
    metadata:
      labels:
        app: practicacd
    spec:
      containers:
      - name: practicacd
        image: fpoirier2020/practicacd:2.0
        imagePullPolicy: Always
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcheck
spec:
  args:
  - name: api-url
    value: http://172.17.0.2:30439/me/version
  metrics:
  - name: webcheck
    failureLimit: 1
    interval: 5s
    successCondition: result == "OK"
    provider:
      web:
        url: "{{ args.api-url }}"
        jsonPath: "{$.status}"
---
apiVersion: v1
kind: Service
metadata:
  name: practicacd
  labels:
    app: practicacd
spec:
  ports:
    - port: 8081
  selector:
    app: practicacd
  type: LoadBalancer